package mocks

import gin "gopkg.in/gin-gonic/gin.v1"
import handlers "github.com/lcollin/covenant/handlers"
import mock "github.com/stretchr/testify/mock"

// SubscriptionI is an autogenerated mock type for the SubscriptionI type
type SubscriptionI struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx
func (_m *SubscriptionI) Delete(ctx *gin.Context) {
	_m.Called(ctx)
}

// New provides a mock function with given fields: ctx
func (_m *SubscriptionI) New(ctx *gin.Context) {
	_m.Called(ctx)
}

// Time provides a mock function with given fields:
func (_m *SubscriptionI) Time() gin.HandlerFunc {
	ret := _m.Called()

	var r0 gin.HandlerFunc
	if rf, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}

	return r0
}

// Update provides a mock function with given fields: ctx
func (_m *SubscriptionI) Update(ctx *gin.Context) {
	_m.Called(ctx)
}

// View provides a mock function with given fields: ctx
func (_m *SubscriptionI) View(ctx *gin.Context) {
	_m.Called(ctx)
}

// ViewAll provides a mock function with given fields: ctx
func (_m *SubscriptionI) ViewAll(ctx *gin.Context) {
	_m.Called(ctx)
}

// ViewByRoaster provides a mock function with given fields: ctx
func (_m *SubscriptionI) ViewByRoaster(ctx *gin.Context) {
	_m.Called(ctx)
}

// ViewByUser provides a mock function with given fields: ctx
func (_m *SubscriptionI) ViewByUser(ctx *gin.Context) {
	_m.Called(ctx)
}

var _ handlers.SubscriptionI = (*SubscriptionI)(nil)
