package mocks

import gin "gopkg.in/gin-gonic/gin.v1"
import handlers "github.com/yuderekyu/covenant/handlers"
import mock "github.com/stretchr/testify/mock"

// SubscriptionI is an autogenerated mock type for the SubscriptionI type
type SubscriptionI struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx
func (_m *SubscriptionI) Delete(ctx *gin.Context) {
	_m.Called(ctx)
}

// New provides a mock function with given fields: ctx
func (_m *SubscriptionI) New(ctx *gin.Context) {
	_m.Called(ctx)
}

// Update provides a mock function with given fields: ctx
func (_m *SubscriptionI) Update(ctx *gin.Context) {
	_m.Called(ctx)
}

// View provides a mock function with given fields: ctx
func (_m *SubscriptionI) View(ctx *gin.Context) {
	_m.Called(ctx)
}

// ViewAll provides a mock function with given fields: ctx
func (_m *SubscriptionI) ViewAll(ctx *gin.Context) {
	_m.Called(ctx)
}

var _ handlers.SubscriptionI = (*SubscriptionI)(nil)
